abbreviation=iXbyq\u2016Abbreviation
grammar=VdQup\u2016Grammar
hyphen=FxusD\u2016Compound words with hyphen
comma=bDa2k\u2016Comma usage
common=MArab\u2016General error
multiword=gFrYp\u2016Multiword expressions
together=CSQye\u2016Together/separately
proofreading=kFDBx\u2016Proofreading
space=8oHz8\u2016Space mistake
typographica=RqxE9\u2016Typographical
dup=FCFDQ\u2016Word duplication
others=3ygV9\u2016Others
numsep=m7eFp\u2016Separation of large numbers (ISO)
quotation=XLh5S\u2016Quotation
