spelling=Kontrola rastniv\u00EEs\u00EA
hlp_grammar=Identify use of grave accent
grammar=Grave accent
hlp_cap=Check missing capitalization of sentences.
cap=Bikaran\u00EEna girdekan
hlp_dup=Check repeated words.
dup=Word duplication
hlp_pair=Check missing or extra parentheses and quotation marks.
pair=Parantez
punctuation=Niqte\u015Fan\u00EE
hlp_spaces=Check single spaces between words.
spaces=Word spacing
hlp_mdash=Force unspaced em dash instead of spaced en dash.
mdash=Em-dash
hlp_ndash=Force spaced en dash instead of unspaced em dash.
ndash=En-dash
hlp_quotation=Dunikan kontrol bikin: "x" \u2192 \u201Cx\u201D
quotation=Quotation marks
hlp_times=Check true multiplication sign: 5x5 \u2192 5\u00D75
times=Multiplication sign
hlp_spaces2=Check single spaces between sentences.
spaces2=Sentence spacing
hlp_spaces3=Check more than two extra space characters between words and sentences.
spaces3=More spaces
hlp_minus=Change hyphen characters to real minus signs.
minus=N\u00EE\u015Fana k\u00EAmek e
hlp_apostrophe=Change typewriter apostrophe, single quotation marks and correct double primes.
apostrophe=Apostrophes
hlp_ellipsis=Replace three dots with ellipsis.
ellipsis=S\u00EAxal
others=\u00CAn din
hlp_metric=Identify redundant terms: "criar novo", "subir para cima", "beco sem sa\u00EDda", "regra geral".
metric=Pleonasms
hlp_gerund=Inadequate use of gerund: "estarei trabalhando", "vou estar fazendo".
gerund=Gerundisms
hlp_nonmetric=Ugly or unpleasant sound: "por cada".
nonmetric=Dengp Kakofon\u00EEk
hlp_paronimo=Words that are pronounced or written in a similar way but which have different lexical meanings.
paronimo=Paronyms
hlp_composto=Compound words written separatedly: "auto escola", "sub contratado".
composto=Compound terms
hlp_malmau=Bikaran\u00EEna "mal" an j\u00EE "mau".
malmau="Mal" an j\u00EE "Mau"
hlp_aha=Bikaran\u00EEna h\u00E1 an j\u00EE a.
aha="H\u00E1" an j\u00EE "a"
hlp_meiameio=Bikaran\u00EEna "meia" an j\u00EE "meio"
meiameio="Meia" an j\u00EE "meio"
hlp_verbo=Peymana devk\u00EE kontrol bike.
verbo=Peymana devk\u00EE
hlp_pronominal=Position that personal pronouns occupy in relation to the verb.
pronominal=Pronominal placement
hlp_pronome=Bikaran\u00EEna c\u00EEnavk\u00EA.
pronome=Bikaran\u00EEna c\u00EEnavkan.
hlp_porque=Check for "porque", "por que", "porqu\u00EA" and "por qu\u00EA".
porque=Bikaran\u00EEna "porqu\u00EA"
