spelling=UbDte\u2016Grammar checking
hlp_grammar=Y3GdR\u2016Identify use of grave accent
grammar=y47wU\u2016Grave accent
hlp_cap=KTKVL\u2016Check missing capitalization of sentences.
cap=czHGi\u2016Capitalization
hlp_dup=6q87h\u2016Check repeated words.
dup=vFbJC\u2016Word duplication
hlp_pair=CkE8A\u2016Check missing or extra parentheses and quotation marks.
pair=DWaBt\u2016Parentheses
punctuation=EJA3T\u2016Punctuation
hlp_spaces=GfJce\u2016Check single spaces between words.
spaces=2Cz8d\u2016Word spacing
hlp_mdash=jh9qT\u2016Force unspaced em dash instead of spaced en dash.
mdash=QUZwx\u2016Em-dash
hlp_ndash=ijU9H\u2016Force spaced en dash instead of unspaced em dash.
ndash=tyEkH\u2016En-dash
hlp_quotation=ZQhno\u2016Check double quotation marks: "x" \u2192 \u201Cx\u201D
quotation=bC8RD\u2016Quotation marks
hlp_times=CARTv\u2016Check true multiplication sign: 5x5 \u2192 5\u00D75
times=Y5eQr\u2016Multiplication sign
hlp_spaces2=ykeAk\u2016Check single spaces between sentences.
spaces2=uHT7U\u2016Sentence spacing
hlp_spaces3=WEAJJ\u2016Check more than two extra space characters between words and sentences.
spaces3=XbDmT\u2016More spaces
hlp_minus=Fthsx\u2016Change hyphen characters to real minus signs.
minus=VNuhF\u2016Minus sign
hlp_apostrophe=nvi9G\u2016Change typewriter apostrophe, single quotation marks and correct double primes.
apostrophe=Daynz\u2016Apostrophes
hlp_ellipsis=5qDDv\u2016Replace three dots with ellipsis.
ellipsis=ngM8A\u2016Ellipsis
others=5dkwv\u2016Others
hlp_metric=ifGmB\u2016Identify redundant terms: "criar novo", "subir para cima", "beco sem sa\u00EDda", "regra geral".
metric=EgY9b\u2016Pleonasms
hlp_gerund=wAFVA\u2016Inadequate use of gerund: "estarei trabalhando", "vou estar fazendo".
gerund=3cDKm\u2016Gerundisms
hlp_nonmetric=eJcDX\u2016Ugly or unpleasant sound: "por cada".
nonmetric=Bidr9\u2016Cacophonous sound
hlp_paronimo=funWi\u2016Words that are pronounced or written in a similar way but which have different lexical meanings.
paronimo=ua58D\u2016Paronyms
hlp_composto=nJ4AT\u2016Compound words written separatedly: "auto escola", "sub contratado".
composto=5TS3y\u2016Compound terms
hlp_malmau=RM535\u2016Use of "mal" or "mau".
malmau=SwvCV\u2016"Mal" or "Mau"
hlp_aha=pC8xk\u2016Use of h\u00E1 or a.
aha=HGVSj\u2016"H\u00E1" or "a"
hlp_meiameio=cBTLG\u2016Use of "meia" or "meio".
meiameio=RxzDW\u2016"Meia" or "meio"
hlp_verbo=bNA4x\u2016Check verbal agreement.
verbo=Ekweu\u2016Verbal agreement
hlp_pronominal=wRBb9\u2016Position that personal pronouns occupy in relation to the verb.
pronominal=FHPjP\u2016Pronominal placement
hlp_pronome=iiTDb\u2016Use of pronoun.
pronome=ETD6e\u2016Use of pronouns
hlp_porque=szSVE\u2016Check for "porque", "por que", "porqu\u00EA" and "por qu\u00EA".
porque=7QjsH\u2016Use of "porqu\u00EA"
