spelling=Asenqed n tjerrumt
hlp_grammar=Identify use of grave accent
grammar=Grave accent
hlp_cap=Senqed isekkilen imeqqranen deg tefyar.
cap=Asekkil ameqqran
hlp_dup=Senqed allus n wawalen
dup=Allus n wawal
hlp_pair=Check missing or extra parentheses and quotation marks.
pair=Tacciwin
punctuation=Asigez
hlp_spaces=Senqed tallunin gar tefyar.
spaces=Ilem gar wawalen
hlp_mdash=Force unspaced em dash instead of spaced en dash.
mdash=Em-dash
hlp_ndash=Force spaced en dash instead of unspaced em dash.
ndash=Ajerri\u1E0D (tizdit
hlp_quotation=Check double quotation marks: "x" \u2192 \u201Cx\u201D
quotation=Quotation marks
hlp_times=Check true multiplication sign: 5x5 \u2192 5\u00D75
times=Multiplication sign
hlp_spaces2=Selken tallunin tasufin gar tefyar.
spaces2=Ilem gar tefyar
hlp_spaces3=Check more than two extra space characters between words and sentences.
spaces3=Tallunin tiya\u1E0D
hlp_minus=Change hyphen characters to real minus signs.
minus=Ticre\u1E0Dt n usenqes
hlp_apostrophe=Change typewriter apostrophe, single quotation marks and correct double primes.
apostrophe=Apostrophes
hlp_ellipsis=Replace three dots with ellipsis.
ellipsis=agazen yemse\u1E0Dfaren
others=Wiya\u1E0D
hlp_metric=Identify redundant terms: "criar novo", "subir para cima", "beco sem sa\u00EDda", "regra geral".
metric=Pleonasms
hlp_gerund=Inadequate use of gerund: "estarei trabalhando", "vou estar fazendo".
gerund=Gerundisms
hlp_nonmetric=Ugly or unpleasant sound: "por cada".
nonmetric=Cacophonous sound
hlp_paronimo=Words that are pronounced or written in a similar way but which have different lexical meanings.
paronimo=Paronyms
hlp_composto=Compound words written separatedly: "auto escola", "sub contratado".
composto=Awal uddis
hlp_malmau=Aseqdec n "mal" ne\u0263 n "mau".
malmau="Mal" ne\u0263 "Mau"
hlp_aha=Aseqdec n h\u00E1 ne\u0263 a.
aha="H\u00E1" ne\u0263 "a"
hlp_meiameio=Aseqdec n "meia" ne\u0263 "meio".
meiameio="Meia" ne\u0263 "meio"
hlp_verbo=Senqed amtawi n yimyagen.
verbo=Amtawa n umyag
hlp_pronominal=Position that personal pronouns occupy in relation to the verb.
pronominal=Adeg n yimqimen
hlp_pronome=Aseqdec n umqim.
pronome=Aseqdec n yimqimen
hlp_porque=Check for "porque", "por que", "porqu\u00EA" and "por qu\u00EA".
porque=Aseqdec n "porqu\u00EA"
