spelling=jFVKx\u2016Spelling
cap=DrGWV\u2016Capitalization
par=z3yr8\u2016Parentheses
wordpart=igaaQ\u2016Word parts of compounds
comma=L5Fo6\u2016Comma usage
proofreading=hgUiH\u2016Proofreading
style=VPQmL\u2016Style checking
compound=tALAw\u2016Underline typo-like compound words
allcompound=sxQau\u2016Underline all generated compound words
grammar=FdR3D\u2016Possible mistakes
money=DPEKs\u2016Consistency of money amounts
duplication=3uXGW\u2016Word duplication
dup0=Y2AD9\u2016Word duplication
dup=gsa8G\u2016Duplication within clauses
dup2=NfAqF\u2016Duplication within sentences
dup3=MHboa\u2016Allow previous checkings with affixes
numpart=CBEZj\u2016Thousand separation of numbers
typography=BSBZA\u2016Typography
quot=MGpiu\u2016Quotation marks
apost=x3GM2\u2016Apostrophe
dash=kcfut\u2016En dash
elli=qbUaJ\u2016Ellipsis
ligature=CmffD\u2016Ligature suggestion
noligature=TwxSo\u2016Underline ligatures
frac=rE4tQ\u2016Fractions
thin=UJKCj\u2016Thin space
spaces=SZQdU\u2016Double spaces
spaces2=FqzDS\u2016More spaces
idx=FVCTr\u2016Indices
minus=E5PBN\u2016Minus
SI=nrJ49\u2016Measurements
hyphen=wAjsS\u2016Hyphenation of ambiguous words
